project:
  title: "data_qa"
  type: website
  
  
  
website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Overview"
        contents:
        - index.qmd
      - section: "Data Types"
        contents:
          - data_types.qmd
      - section: "Too much or too little"
        contents:
          - missing_data.qmd   
          - duplicate_data.qmd 
      - section: "Wrong data"
        contents:
          - data_in_range.qmd  
          - spelling_counts.qmd 
          - geocoordinates.qmd 



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual



