project:
  title: "data_qa"
  type: website
  output-dir: docs
  
  
  
website:
  repo-url: https://github.com/quarto-dev/quarto-demo
  repo-actions: [issue]
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    contents:
        - index.qmd
        - setup.qmd
        - data_types.qmd
        - missing_data.qmd   
        - duplicate_data.qmd 
        - data_in_range.qmd  
        - spelling_counts.qmd 
        - geocoordinates.qmd 
        - time_zones.qmd 
        - logic_tests.qmd 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true

editor: visual



