project:
  title: "data_qa"
  type: website
  
  
  
website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Overview"
        contents:
        - index.qmd
      - section: "Basics"
        contents:
          - data_types.qmd
      - section: "Layout"
        contents:
          - missing_data.qmd   
          



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual



